const express = require("express");
const fs = require("fs");
const csv = require("csv-parser");

const app = express();
const port = 3000;

const validCountries = new Set([
  // ใส่รายชื่อประเทศที่ถูกต้องทั้งหมด
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
]);

const countryRegions = {
  Afghanistan: "Asia",
  Albania: "Europe",
  Algeria: "Africa",
  Andorra: "Europe",
  Angola: "Africa",
  "Antigua and Barbuda": "Americas",
  Argentina: "Americas",
  Armenia: "Asia",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "Asia",
  Bahamas: "Americas",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Barbados: "Americas",
  Belarus: "Europe",
  Belgium: "Europe",
  Belize: "Americas",
  Benin: "Africa",
  Bhutan: "Asia",
  Bolivia: "Americas",
  "Bosnia and Herzegovina": "Europe",
  Botswana: "Africa",
  Brazil: "Americas",
  Brunei: "Asia",
  Bulgaria: "Europe",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  "Cabo Verde": "Africa",
  Cambodia: "Asia",
  Cameroon: "Africa",
  Canada: "Americas",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Chile: "Americas",
  China: "Asia",
  Colombia: "Americas",
  Comoros: "Africa",
  Congo: "Africa",
  "Costa Rica": "Americas",
  Croatia: "Europe",
  Cuba: "Americas",
  Cyprus: "Asia",
  "Czech Republic": "Europe",
  "Democratic Republic of the Congo": "Africa",
  Denmark: "Europe",
  Djibouti: "Africa",
  Dominica: "Americas",
  "Dominican Republic": "Americas",
  Ecuador: "Americas",
  Egypt: "Africa",
  "El Salvador": "Americas",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Estonia: "Europe",
  Eswatini: "Africa",
  Ethiopia: "Africa",
  Fiji: "Oceania",
  Finland: "Europe",
  France: "Europe",
  Gabon: "Africa",
  Gambia: "Africa",
  Georgia: "Asia",
  Germany: "Europe",
  Ghana: "Africa",
  Greece: "Europe",
  Grenada: "Americas",
  Guatemala: "Americas",
  Guinea: "Africa",
  "Guinea-Bissau": "Africa",
  Guyana: "Americas",
  Haiti: "Americas",
  Honduras: "Americas",
  Hungary: "Europe",
  Iceland: "Europe",
  India: "Asia",
  Indonesia: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Ireland: "Europe",
  Israel: "Asia",
  Italy: "Europe",
  "Ivory Coast": "Africa",
  Jamaica: "Americas",
  Japan: "Asia",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kenya: "Africa",
  Kiribati: "Oceania",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  Laos: "Asia",
  Latvia: "Europe",
  Lebanon: "Asia",
  Lesotho: "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Madagascar: "Africa",
  Malawi: "Africa",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mali: "Africa",
  Malta: "Europe",
  "Marshall Islands": "Oceania",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Mexico: "Americas",
  Micronesia: "Oceania",
  Moldova: "Europe",
  Monaco: "Europe",
  Mongolia: "Asia",
  Montenegro: "Europe",
  Morocco: "Africa",
  Mozambique: "Africa",
  Myanmar: "Asia",
  Namibia: "Africa",
  Nauru: "Oceania",
  Nepal: "Asia",
  Netherlands: "Europe",
  "New Zealand": "Oceania",
  Nicaragua: "Americas",
  Niger: "Africa",
  Nigeria: "Africa",
  "North Korea": "Asia",
  "North Macedonia": "Europe",
  Norway: "Europe",
  Oman: "Asia",
  Pakistan: "Asia",
  Palau: "Oceania",
  Palestine: "Asia",
  Panama: "Americas",
  "Papua New Guinea": "Oceania",
  Paraguay: "Americas",
  Peru: "Americas",
  Philippines: "Asia",
  Poland: "Europe",
  Portugal: "Europe",
  Qatar: "Asia",
  Romania: "Europe",
  Russia: "Europe",
  Rwanda: "Africa",
  "Saint Kitts and Nevis": "Americas",
  "Saint Lucia": "Americas",
  "Saint Vincent and the Grenadines": "Americas",
  Samoa: "Oceania",
  "San Marino": "Europe",
  "Sao Tome and Principe": "Africa",
  "Saudi Arabia": "Asia",
  Senegal: "Africa",
  Serbia: "Europe",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Singapore: "Asia",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "Solomon Islands": "Oceania",
  Somalia: "Africa",
  "South Africa": "Africa",
  "South Korea": "Asia",
  "South Sudan": "Africa",
  Spain: "Europe",
  "Sri Lanka": "Asia",
  Sudan: "Africa",
  Suriname: "Americas",
  Sweden: "Europe",
  Switzerland: "Europe",
  Syria: "Asia",
  Taiwan: "Asia",
  Tajikistan: "Asia",
  Tanzania: "Africa",
  Thailand: "Asia",
  "Timor-Leste": "Asia",
  Togo: "Africa",
  Tonga: "Oceania",
  "Trinidad and Tobago": "Americas",
  Tunisia: "Africa",
  Turkey: "Asia",
  Turkmenistan: "Asia",
  Tuvalu: "Oceania",
  Uganda: "Africa",
  Ukraine: "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States": "Americas",
  Uruguay: "Americas",
  Uzbekistan: "Asia",
  Vanuatu: "Oceania",
  "Vatican City": "Europe",
  Venezuela: "Americas",
  Vietnam: "Asia",
  Yemen: "Asia",
  Zambia: "Africa",
  Zimbabwe: "Africa",
};

app.get("/", (req, res) => {
  res.send("Population API");
});

app.get("/population", (req, res) => {
  const results = {};

  fs.createReadStream("api/population-and-demography.csv")
    .pipe(csv())
    .on("data", (data) => {
      const year = data.Year;
      const countryName = data["Country name"];

      if (validCountries.has(countryName)) {
        if (!results[year]) {
          results[year] = [];
        }
        results[year].push({
          country_name: countryName,
          population: parseInt(data.Population, 10),
          region: countryRegions[countryName] || "Unknown",
        });
      }
    })
    .on("end", () => {
      // Sorting populations within each year in descending order
      for (const year in results) {
        results[year].sort((a, b) => b.population - a.population);
      }
      res.json(results);
    })
    .on("error", (err) => {
      console.error("Error reading CSV file:", err);
      res.status(500).send("Internal Server Error");
    });
});

app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
